### PR TITLE
Add styling and update readme

### PR DESCRIPTION
**Pull request by VasekS**
I've created a new gif file and added it to the assets folder. Feel free to add this gif to your hosting service (same as you did the previous ones) to save space if needed.

### CODE REVIEW

**Comment by ratnakar5938** [comment]
Remove the horizontal bars and also center aligned is not looking good😶

**Review by ratnakar5938 — CHANGES_REQUESTED** [review]
don't change the allcontributors part

**Comment by ratnakar5938** [comment]
also the gif and screenshots are not visible

**Comment by VasekS** [comment]
Hey @ratnakar5938, I went ahead and removed the horizontal bars and the centered alignement.

For the new demo gif it's currently pointing here: https://github.com/ratnakar5938/Youtube-clone/tree/master/public/assets/YouTube-Clone.gif However this won't be visible until those changes are pushed to master since it's pointing to the live repo. I didn't want to use my hosting services since it doesn't make sense to you my credentials in your project. 

The new demo gif is located in public > assets folder so feel free to upload to your hosting and send over the link so I can update the path

**Comment by ratnakar5938** [comment]
> Hey @ratnakar5938, I went ahead and removed the horizontal bars and the centered alignement.
> 
> For the new demo gif it's currently pointing here: https://github.com/ratnakar5938/Youtube-clone/tree/master/public/assets/YouTube-Clone.gif However this won't be visible until those changes are pushed to master since it's pointing to the live repo. I didn't want to use my hosting services since it doesn't make sense to you my credentials in your project. 
> 
> The new demo gif is located in public > assets folder so feel free to upload to your hosting and send over the link so I can update the path

Put the gif location relative to the readme
It will be better

**Review by ratnakar5938 — APPROVED** [review]

**Comment by ratnakar5938** [comment]
happy coding🚀🚀

**Comment by ratnakar5938** [comment]
@all-contributors please add @VasekS  for Doc

**Pull request merged**
